In [0]:
#Q2-> Univariate)

from sklearn.datasets import load_wine

In [0]:
import numpy as np
import pandas as pd

In [0]:
wine= load_wine()
#wine


In [0]:
DF = pd.DataFrame(wine.data, columns=wine.feature_names)
#DF

In [0]:
from sklearn.model_selection import train_test_split


X = wine['data']
Y = wine['target']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.4)



In [0]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [0]:
from sklearn.neural_network import MLPClassifier
MLPobj = MLPClassifier(hidden_layer_sizes=(50), activation='tanh', alpha =0.009, max_iter=250 )
MLPobj.fit(X_train,Y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='tanh', alpha=0.009, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=50, learning_rate='constant',
       learning_rate_init=0.001, max_iter=250, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [0]:
predictions = MLPobj.predict(X_test)
MLPobj.score(X_test,Y_test)


0.9722222222222222

In [0]:

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))

[[27  0  0]
 [ 0 31  2]
 [ 0  0 12]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        27
          1       1.00      0.94      0.97        33
          2       0.86      1.00      0.92        12

avg / total       0.98      0.97      0.97        72

